version: '3.8'
services:
  mariadb:
    container_name: docker_mariadb_${APP_NAME}
    image: mariadb:latest
    ports:
    - ${DB_PORT}:3306
    volumes:
    - ./mariadb:/var/lib/mysql
    environment:
    - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MARIADB_USER=${DB_USERNAME}
    - MARIADB_PASSWORD=${DB_PASSWORD}
    - MARIADB_DATABASE=${DB_NAME}
  
  phpmyadmin:
    container_name: docker_phpmyadmin_${APP_NAME}
    image: phpmyadmin:latest
    ports:
    - ${PMA_PORT}:80
    environment:
    - PMA_ARBITRARY=1
