import ChakraUiProvider from '@/components/providers/ChakraUiProvider';
import TanStackProvider from '@/components/providers/TanStackProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'VeriSign',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanStackProvider>
                    <ChakraUiProvider>
                        {children}
                    </ChakraUiProvider>
                </TanStackProvider>
            </body>
        </html>
    );
}
